# When built on Travis, Coveralls can detect the associated repo automatically.
# If you're running locally, you must have a .coveralls.yml file with your repo_token in it; 
# or, you must provide a COVERALLS_REPO_TOKEN environment-variable on the command-line.

# The secret repo token for your repository, found at the bottom of your repository's page on Coveralls. 
# DON'T ADD THIS TO PUBLIC REPO. Should be kept SECRET - anyone could use it to submit coverage data on your repo's behalf.
repo_token: M72blWjnMP2sDHNRx3MocfY3vtdDpZ6Wj
