sudo: required

language: python

python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6

before_script:
  - sudo apt-get install libssl-dev
  - sudo apt-get install python-dev python3-dev

before_install:
  - python -m easy_install -U setuptools
  
install: python setup.py install

script: python setup.py test
