language: python

env:
    - BCL_CONFIG_FILE=config.ini.unittest
python:
    - 3.5
    - 3.6
jobs:
  include:
    # Test ecdsa and pyscrypt for systems where fastecdsa and/or scrypt are not available
    - python: 3.7
      dist: bionic
      env:
        - USING_MODULE_SCRYPT=False
        - USE_FASTECDSA=False
        - UNITTESTS_FULL_DATABASE_TEST=False
      before_script:
        - pip install ecdsa
        - pip install pyscrypt
    # Enable 3.8 without globally enabling sudo and dist: xenial for other build jobs
    - python: 3.8
      dist: xenial
      env:
        - UNITTESTS_FULL_DATABASE_TEST=True

before_install:
  - sudo apt-get install -y postgresql postgresql-contrib
  - sudo apt-get install -y mysql-server
  - sudo service postgresql start
  - sudo service mysql start

install:
  - pip install coveralls
  - pip install scrypt
  - pip install psycopg2
  - pip install mysql-connector
  - pip install mysqlclient
  - pip install parameterized
  - python setup.py install

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then coverage run --source=bitcoinlib setup.py test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python setup.py test ; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then coveralls ; fi
