sudo: required

language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7.1
      dist: xenial
      sudo: true

before_script:
  - sudo apt-get install libssl-dev
  - sudo apt-get install python-dev python3-dev

install:
  - pip install scrypt
  - python setup.py install

script: python setup.py test
