sudo: required

language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7.1
      dist: xenial
      sudo: true
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel

install:
  - pip install scrypt
  - python setup.py install

script: python setup.py test
