
name: Bitcoinlib Unittests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install coveralls
          pip install psycopg2
          pip install mysql-connector
          pip install mysqlclient
          pip install parameterized
          python setup.py install
      - name: Test ${{ matrix.python }}
        env:
          BCL_CONFIG_FILE: config.ini.unittest
          UNITTESTS_FULL_DATABASE_TEST: False
        run: coverage run --source=bitcoinlib -m unittest -v
       - name: Coveralls Parallel
       uses: coverallsapp/github-action@v2
       with:
         github-token: ${{ secrets.github_token }}
         flag-name: run-${{ matrix.test_number }}
         parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
