name: Bitcoinlib Unittests Coveralls Ubuntu - No scrypt
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install coveralls
          pip install psycopg2
          pip install mysql-connector
          pip install mysqlclient
          pip install parameterized
          pip install Cython
          python setup.py install
      - name: Test with coverage
        env:
          BCL_CONFIG_FILE: config_encryption.ini.unittest
          UNITTESTS_FULL_DATABASE_TEST: False
          DB_FIELD_ENCRYPTION_KEY: 11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff
        run: coverage run --source=bitcoinlib -m unittest -v
