name: Bitcoinlib Tests Ubuntu - No scrypt
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install .[dev]
          pip uninstall -y scrypt
      - name: Test with coverage
        env:
          BCL_CONFIG_FILE: ${{ github.workspace }}/config_encryption.ini.unittest
          DB_FIELD_ENCRYPTION_KEY: 11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff
        run: coverage run --source=bitcoinlib -m unittest -v
