name: Bitcoinlib Tests Windows
on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install .[dev]
      - name: Test with coverage
        env:
          BCL_CONFIG_FILE: ${{ github.workspace }}/tests/config.ini.unittest
          PYTHONUTF8: 1
        run: coverage run --source=bitcoinlib -m unittest -v
