
name: Bitcoinlib Unittests

on: [push]

jobs:
  build:

    strategy:
      matrix:
#        python: ["3.6", "3.7", "3.8", "3.9"]
        python: ["3.9"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'
      - name: Install packages
        run: |
          sudo systemctl start mysql.service
      - name: Install dependencies
        run: |
          pip install coveralls
          pip install psycopg2
          pip install mysql-connector
          pip install mysqlclient
          pip install parameterized
          python setup.py install
      - name: Test with covarage
        env:
          BCL_CONFIG_FILE: config.ini.unittest
          UNITTESTS_FULL_DATABASE_TEST: True
        run: coverage run --source=bitcoinlib -m unittest -v
