name: Bitcoinlib Tests Ubuntu - MySQL
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: test
          MARIADB_USER: user
          MARIADB_PASSWORD: password
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        python: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install .[dev]
    - name: Test with coverage
      env:
        BCL_CONFIG_FILE: config.ini.unittest
        UNITTESTS_FULL_DATABASE_TEST: False
        UNITTEST_DATABASE: mysql
      run: coverage run --source=bitcoinlib -m unittest -v

    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Test
        debug: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: true
