name: Bitcoinlib Tests Ubuntu - MySQL
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
          architecture: 'x64'
    - name: Set up MySQL
      env:
        DB_DATABASE: bitcoinlib_test
        DB_USER: root
        DB_PASSWORD: root
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Install dependencies
      run: |
        python -m pip install .[dev]
    - name: Test with coverage
      env:
        BCL_CONFIG_FILE: ${{ github.workspace }}/config.ini.unittest
        UNITTEST_DATABASE: mysql
      run: coverage run --source=bitcoinlib -m unittest -v
